# Generated by Django 6.0 on 2025-12-12 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_issuing_country', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('health_conditions', models.TextField(blank=True, null=True)),
                ('frequent_traveler', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traveler_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
